version: "3.9"
name: "ai-alerting-dev"
services:
    server:
        build:
            context: ./
            dockerfile: ./src/server/Dockerfile
        restart: unless-stopped
        volumes:
            - .:/server
        ports:
            - 8000:8000
        # env_file:
        #     - ./.env
