# Generated by Django 5.0.3 on 2024-03-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(max_length=85),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('external_id', models.PositiveIntegerField()),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feeds.location')),
            ],
        ),
    ]
